name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Setup ESLint configuration
      run: |
        echo '{
          "extends": "next/core-web-vitals",
          "ignorePatterns": ["node_modules/", ".next/", "out/"],
          "rules": {
            "react/no-unescaped-entities": "off",
            "@next/next/no-img-element": "off"
          }
        }' > .eslintrc.json
    
    - name: Run linters
      run: npm run lint || echo "Lint finished with warnings"
      
    - name: Build application
      run: npm run build
      
    - name: Check build output
      run: ls -la .next

  deploy:
    needs: test
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to Easypanel
      uses: fjogeleit/http-request-action@v1
      with:
        url: ${{ secrets.EASYPANEL_WEBHOOK_URL }}
        method: 'POST'
        bearerToken: ${{ secrets.EASYPANEL_API_TOKEN }}
        data: >
          {
            "repository": "${{ github.repository }}",
            "branch": "master",
            "commit": "${{ github.sha }}"
          } 